CREATE TABLE usuarios (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(256) NOT NULL,
	email VARCHAR(256) NOT NULL UNIQUE,
	senha VARCHAR(256) NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

